### ISSUE TITLE
[게임] 효과음 개발

### ISSUE THREAD

**Issue by codejs-kr** [maybe-picasso/picasso#49]
게임에 사용되는 사운드를 실행 할 수 있는 Sound 클래스 인터페이스 개발
### 사운드

- [ ] #59
- [ ] #60
- [ ] #61
- [ ] #62
- [x] #52
- [ ] #63

**Comment by code-sign** [comment]
`use-sound` 라는게 있네요 👀
https://github.com/joshwcomeau/use-sound
https://use-sound.netlify.app/?path=/story/usesound--simple

**Comment by lotstar87** [comment]
@code-sign 오 ㅎㅎ 직접 만들고 있었는데 ㅋㅋ 이거 써야겠네요
